# Generated by Django 6.0.2 on 2026-02-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='branding/'),
        ),
    ]
